## Mounted the google drive

In [23]:
import sys
# path_data = '/home/dal387552/work/Sleep_staging/fitbit'
# path_code = '/home/dal387552/work/SS_codes/sleep_staging'
path_code = '/Users/raghvendraomer/Projects/Sleep_Staging/sleep_staging'
path_data = '/Users/raghvendraomer/Projects/Sleep_Staging/fitbit'
sys.path.insert(0, path_code)

## Prepocess Steps

In [ ]:
from pre_processing.fitbit_preprocessing import prepare_fitbit_training_data_from_file_lists

sleep_paths = [
    f"{path_data}/sleep-data/0a85fd46-fada-434c-9f7a-08b81f9ed8e7.csv.gz"
]
heart_paths = [
    f"{path_data}/heart-rate/0a85fd46-fada-434c-9f7a-08b81f9ed8e7.csv.gz",
]
dataset = prepare_fitbit_training_data_from_file_lists(
    sleep_paths=sleep_paths,
    heart_paths=heart_paths,
    window_sec=128,
    epoch_sec=30,
    sampling_hz=2.0,
    centered=True,
    normalize_per_night=True,
    normalize_per_window=False,
)

X = dataset.X
y = dataset.y
patient_ids = dataset.patient_ids
timestamps = dataset.timestamps

In [7]:
print(X.shape)
print(y.shape)
for i in range(1,10):
    print(X[i][0:3],y[i], patient_ids[i], timestamps[i], dataset.window_starts[i], dataset.window_ends[i])
# print(X, y, patient_ids, timestamps,dataset.window_starts)

(47955, 256)
(47955,)
[2.840329  2.8921924 2.944056 ] 1 0a85fd46-fada-434c-9f7a-08b81f9ed8e7 2018-04-09 23:22:30 2018-04-09 23:21:26 2018-04-09 23:23:34
[1.7511934 1.7252617 1.6993299] 1 0a85fd46-fada-434c-9f7a-08b81f9ed8e7 2018-04-09 23:23:00 2018-04-09 23:21:56 2018-04-09 23:24:04
[1.0769668 1.0769668 1.0769668] 1 0a85fd46-fada-434c-9f7a-08b81f9ed8e7 2018-04-09 23:23:30 2018-04-09 23:22:26 2018-04-09 23:24:34
[0.9732396 0.9473078 0.921376 ] 1 0a85fd46-fada-434c-9f7a-08b81f9ed8e7 2018-04-09 23:24:00 2018-04-09 23:22:56 2018-04-09 23:25:04
[0.66205806 0.68798983 0.71392167] 1 0a85fd46-fada-434c-9f7a-08b81f9ed8e7 2018-04-09 23:24:30 2018-04-09 23:23:26 2018-04-09 23:25:34
[0.5583309 0.5583309 0.5583309] 1 0a85fd46-fada-434c-9f7a-08b81f9ed8e7 2018-04-09 23:25:00 2018-04-09 23:23:56 2018-04-09 23:26:04
[0.5583309 0.5583309 0.5583309] 1 0a85fd46-fada-434c-9f7a-08b81f9ed8e7 2018-04-09 23:25:30 2018-04-09 23:24:26 2018-04-09 23:26:34
[0.5583309  0.545365   0.53239906] 1 0a85fd46-fada-434c-9f7a-08b81f9ed8e7 2018-04-09 23:26:00 2018-04-09 23:24:56 2018-04-09 23:27:04
[0.8176488 0.8176488 0.8176488] 1 0a85fd46-fada-434c-9f7a-08b81f9ed8e7 2018-04-09 23:26:30 2018-04-09 23:25:26 2018-04-09 23:27:34

In [22]:
print(y[10:30])
import numpy as np
print(np.unique(y))
print(X[2])

[1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2]
[0 1 2 3]
[60.       60.       60.       60.       60.       60.066666 60.133335
 60.2      60.266666 60.333332 60.4      60.466667 60.533333 60.6
 60.666668 60.733334 60.8      60.866665 60.933334 61.       62.
 63.       64.       65.       66.       66.4      66.8      67.2
 67.6      68.       67.8      67.6      67.4      67.2      67.
 66.86667  66.73333  66.6      66.46667  66.333336 66.2      66.066666
 65.933334 65.8      65.666664 65.53333  65.4      65.26667  65.13333
 65.       64.6      64.2      63.8      63.4      63.       62.8
 62.6      62.4      62.2      62.      ]

In [ ]:
from pre_processing.fitbit_preprocessing import prepare_fitbit_training_data_from_directories

dataset = prepare_fitbit_training_data_from_directories(
    sleep_dir="/Users/raghvendraomer/Projects/Sleep_Staging/fitbit/sleep-data",
    heart_dir="/Users/raghvendraomer/Projects/Sleep_Staging/fitbit/heart-rate",
    window_sec=60,
    epoch_sec=30,
    sampling_hz=1.0,
    centered=True,
)

X = dataset.X
y = dataset.y
patient_ids = dataset.patient_ids
timestamps = dataset.timestamps

print("X shape:", X.shape)
print("y shape:", y.shape)
print("patient_ids shape:", patient_ids.shape)
print("classes:", dataset.stage_names)



# dataset = prepare_fitbit_training_data_from_directories(
#     sleep_dir="/path/to/sleep-data",
#     heart_dir="/path/to/heart-rate",
#     window_sec=128,
#     epoch_sec=30,
#     sampling_hz=2.0,
#     centered=True,
#     normalize_per_night=True,
#     normalize_per_window=False,
# )

## Reading the sleep Data

In [2]:
# Then read from it
import pandas as pd
df_sleep = pd.read_csv("drive/MyDrive/fitbit/sleep-data/02581754-36cd-4b23-85ea-bf995c6dec83.csv.gz", compression='gzip')
display(df_sleep.head(30))

    sleepId                 dateTime     level  seconds
0         1  2018-04-08T22:22:30.000    asleep     4980
1         1  2018-04-08T23:45:30.000  restless       60
2         1  2018-04-08T23:46:30.000    asleep     2040
3         1  2018-04-09T00:20:30.000  restless      120
4         1  2018-04-09T00:22:30.000    asleep      120
5         1  2018-04-09T00:24:30.000  restless       60
6         1  2018-04-09T00:25:30.000    asleep      480
7         1  2018-04-09T00:33:30.000  restless       60
8         1  2018-04-09T00:34:30.000    asleep      120
9         1  2018-04-09T00:36:30.000  restless      120
10        1  2018-04-09T00:38:30.000    asleep     1980
11        1  2018-04-09T01:11:30.000  restless       60
12        1  2018-04-09T01:12:30.000    asleep      240
13        1  2018-04-09T01:16:30.000  restless       60
14        1  2018-04-09T01:17:30.000    asleep      300
15        1  2018-04-09T01:22:30.000  restless      180
16        1  2018-04-09T01:25:30.000    asleep      420
17        1  2018-04-09T01:32:30.000  restless      120
18        1  2018-04-09T01:34:30.000    asleep      420
19        1  2018-04-09T01:41:30.000  restless       60
20        1  2018-04-09T01:42:30.000    asleep       60
21        1  2018-04-09T01:43:30.000  restless       60
22        1  2018-04-09T01:44:30.000    asleep      480
23        1  2018-04-09T01:52:30.000  restless       60
24        1  2018-04-09T01:53:30.000    asleep       60
25        1  2018-04-09T01:54:30.000  restless      120
26        1  2018-04-09T01:56:30.000    asleep      360
27        1  2018-04-09T02:02:30.000  restless      120
28        1  2018-04-09T02:04:30.000    asleep      120
29        1  2018-04-09T02:06:30.000  restless      120

In [4]:
# Then read from it
import pandas as pd
df_heart = pd.read_csv("drive/MyDrive/fitbit/heart-rate/02581754-36cd-4b23-85ea-bf995c6dec83.csv.gz", compression='gzip')
display(df_heart.head(30))

                  Timestamp  HeartRatePPG
0   2018-04-09T00:00:02.000          62.0
1   2018-04-09T00:00:07.000          62.0
2   2018-04-09T00:00:12.000          61.0
3   2018-04-09T00:00:22.000          62.0
4   2018-04-09T00:00:37.000          62.0
5   2018-04-09T00:00:42.000          63.0
6   2018-04-09T00:00:47.000          64.0
7   2018-04-09T00:00:52.000          62.0
8   2018-04-09T00:00:57.000          61.0
9   2018-04-09T00:01:02.000          60.0
10  2018-04-09T00:01:07.000          62.0
11  2018-04-09T00:01:12.000          63.0
12  2018-04-09T00:01:27.000          59.0
13  2018-04-09T00:01:32.000          60.0
14  2018-04-09T00:01:37.000          61.0
15  2018-04-09T00:01:42.000          62.0
16  2018-04-09T00:01:57.000          62.0
17  2018-04-09T00:02:02.000          61.0
18  2018-04-09T00:02:07.000          60.0
19  2018-04-09T00:02:12.000          61.0
20  2018-04-09T00:02:27.000          61.0
21  2018-04-09T00:02:32.000          60.0
22  2018-04-09T00:02:37.000          62.0
23  2018-04-09T00:02:47.000          61.0
24  2018-04-09T00:02:57.000          62.0
25  2018-04-09T00:03:02.000          61.0
26  2018-04-09T00:03:09.000          61.0
27  2018-04-09T00:03:14.000          62.0
28  2018-04-09T00:03:19.000          61.0
29  2018-04-09T00:03:29.000          62.0